modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/awitkowski0/Cobblemon-Nuzlocke/issues"
license = "MIT License"

[[mods]]
modId = "nuzlocke"
version = "${version}"
displayName = "Cobblemon: Nuzlocke"
authors = "funalex"
description = '''
Nuzlocke addon for cobblemon
'''
#logoFile = ""

[[dependencies.nuzlocke]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.nuzlocke]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nuzlocke]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6,)"
ordering = "AFTER"
side = "BOTH"
