have_fun: false
memory_config:
  disabled: false
code_review:
  disable: false
  comment_severity_threshold: HIGH
  max_review_comments: 3
  pull_request_opened:
    help: false
    summary: false
    code_review: true
    include_drafts: true
ignore_patterns:
  - "*.py"
  - "**/*.py"
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.jpeg"
  - "**/*.svg"
  - "**/*.gif"
  - "**/*.ico"
  - "**/*.webp"
  - "**/*.geo.json"
